name: example
description: A new Flutter project.
publish_to: 'none'
version: 2.0.1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  github_colour:
    path: '../'
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.5
dev_dependencies:
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
