name: github_colour
description: Receive ozh's GitHub colour to Flutter's colour implementation with caching and fallback.
version: 3.0.0
repository: https://github.com/rk0cc/github_colour_flutter
topics:
  - color
  - colour
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.0.15
  lzma: ^1.0.1
  shared_preferences: ^2.1.1
  hashlib: ^1.11.4
flutter:
  uses-material-design: true
  assets:
    - packages/github_colour/colors.json
