name: github_colour
description: Receive GitHub colour to Flutter's colour object
version: 0.1.0
homepage: https://www.rk0cc.xyz
repository: https://github.com/rk0cc/github_colour_flutter
environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  meta: ^1.7.0
  path: ^1.8.1
  path_provider: ^2.0.9
  lzma: ^1.0.1
  shared_preferences: ^2.0.13
flutter:
  uses-material-design: true
