name: github_colour
description: Receive ozh's GitHub colour to Flutter's colour implementation with caching and fallback.
version: 3.2.2
repository: https://github.com/rk0cc/github_colour_flutter
topics:
  - color
  - colour
screenshots:
  - description: 'C++ colour applied'
    path: screenshots/6qOSnXq.png
  - description: 'Java colour applied'
    path: screenshots/6Ho6RyT.png
  - description: 'Golang colour applied'
    path: screenshots/Ksf3x3o.png
  - description: 'Dart colour applied'
    path: screenshots/uSiOYUF.png
  - description: 'Python colour applied'
    path: screenshots/yaTEp1i.png
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.1.1
  lzma: ^1.0.1
  sembast: ^3.7.0
  sembast_web: ^2.3.0
  hashlib: ^1.12.0
dev_dependencies: 
  flutter_lints: ">=3.0.1 <5.0.0"
platforms:
  android:
  ios:
  windows:
  macos:
  linux:
  web:
flutter:
  uses-material-design: true
  assets:
    - packages/github_colour/colors.json
